"""Read the static website in website/ for the tests: a tiny element tree, standard library only."""

from __future__ import annotations

import shlex
from dataclasses import dataclass, field
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEBSITE = ROOT / "website"
VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "source",
        "track", "wbr", "path", "circle", "rect", "line", "polyline", "polygon", "ellipse",
        "stop", "use"}


@dataclass
class Element:
    tag: str
    attrs: dict
    parent: Element | None = None
    children: list = field(default_factory=list)  # Element or str

    def text(self) -> str:
        return "".join(c if isinstance(c, str) else c.text() for c in self.children)

    def iter(self):
        yield self
        for c in self.children:
            if isinstance(c, Element):
                yield from c.iter()

    def ancestors(self):
        node = self.parent
        while node is not None:
            yield node
            node = node.parent

    def classes(self) -> set[str]:
        return set((self.attrs.get("class") or "").split())


class _TreeBuilder(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.root = Element("#document", {})
        self.node = self.root

    def handle_starttag(self, tag, attrs):
        el = Element(tag, {k: (v if v is not None else "") for k, v in attrs}, self.node)
        self.node.children.append(el)
        if tag not in VOID:
            self.node = el

    def handle_startendtag(self, tag, attrs):
        self.node.children.append(
            Element(tag, {k: (v if v is not None else "") for k, v in attrs}, self.node))

    def handle_endtag(self, tag):
        node = self.node
        while node is not self.root and node.tag != tag:
            node = node.parent
        if node is not self.root:
            self.node = node.parent

    def handle_data(self, data):
        self.node.children.append(data)


def parse(path: Path) -> Element:
    builder = _TreeBuilder()
    builder.feed(path.read_text(encoding="utf-8"))
    builder.close()
    return builder.root


def pages() -> list[Path]:
    """Every HTML page of the site (the example reports are linked, not part of website/)."""
    return sorted(p for p in WEBSITE.rglob("*.html") if "examples" not in p.relative_to(
        WEBSITE).parts)


# reference, own-metric and assistant come from docs/*.md (scripts/render_reference.py).
GENERATED_PAGES = {"reference.html", "own-metric.html", "assistant.html"}
# The navigation bar every page carries, in order: (href, label).
NAV = [("index.html", "Home"), ("own-metric.html", "Your own metric"), ("start.html", "Use it on your app"), ("assistant.html", "With a coding assistant"),
       ("reference.html", "Reference"), ("https://github.com/judgekeeper/judgekeeper", "GitHub")]


def hand_written_pages() -> list[Path]:
    """Pages written by hand, not generated by a script in scripts/."""
    return [p for p in pages() if p.name not in GENERATED_PAGES]


def in_output(el: Element) -> bool:
    """Inside a block that shows what a command printed, not a command to type."""
    return any("output" in a.classes() for a in [el, *el.ancestors()])


def command_lines(text: str) -> list[str]:
    """Join backslash continuations and return the non-empty lines."""
    lines, current = [], ""
    for raw in text.splitlines():
        line = raw.rstrip()
        if line.endswith("\\"):
            current += line[:-1] + " "
            continue
        current += line
        if current.strip():
            lines.append(current.strip())
        current = ""
    if current.strip():
        lines.append(current.strip())
    return lines


def judgekeeper_argv(line: str) -> list[str] | None:
    """The arguments after `judgekeeper` in a shell line, or None if it does not run judgekeeper.

    Accepts `VAR=value judgekeeper ...`, `uvx judgekeeper ...` and
    `uvx --from <source> judgekeeper ...`. Shell comments are dropped.
    """
    try:
        words = shlex.split(line, comments=True)
    except ValueError:
        return None
    while words and "=" in words[0] and not words[0].startswith("-"):
        words = words[1:]  # environment assignments such as PYTHONPATH=.
    if words[:1] == ["uvx"]:
        words = words[1:]
        if words[:1] == ["--from"]:
            words = words[2:]
    if words[:1] != ["judgekeeper"]:
        return None
    return words[1:]


def commands(path: Path) -> list[tuple[str, list[str]]]:
    """(line, argv) for every judgekeeper command in a <code> element outside output blocks."""
    found = []
    for el in parse(path).iter():
        if el.tag != "code" or in_output(el):
            continue
        for line in command_lines(el.text()):
            argv = judgekeeper_argv(line)
            if argv is not None:
                found.append((line, argv))
    return found
